Add 'input' to list of reserved words
hedyorg/hedy pull request #3462
Opened 2022-10-19 20:14 UTC by JonathanMurray

**Description**

Adds 'input' to the list of reserved words, as it's a Python method that our generated code can call.

**Fixes _issue or discussion number_**

Fixes https://github.com/Felienne/hedy/issues/3454 (I think and hope)

**How to test**

This program fails on level 11 before the change but should succeed after it:
```
input = "some string"
x = ask "question"
```

**Checklist**
Done? Check if you have it all in place using this list:*
  
- [ ] Describes changes in the format above (present tense)
- [ ] Links to an existing issue or discussion 
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

2022-10-19 20:37 UTC, JonathanMurray commented
Looking at the list of reserved words, I notice that it seems to cover language keywords but no (or few) function names. Is there some specific reason for not including those, or has it just not been an issue yet?

It seems like errors similar to the one encountered in https://github.com/Felienne/hedy/issues/3454 can be reproduced for many such function names:

(level 11)

('str' object is not callable)
```
int = 1
int = int + 1
print int
```

('str' object has no attribute 'sleep')
```
time = "04:00"
for i in range 0 to 1
    print "good morning"
```

('str' object is not callable)
```
convert_numerals = "yes"
if convert_numerals == "yes"
    print "Let's convert some numerals!"
```
(admittedly a far-fetched example hehe)

2022-10-20 06:46 UTC, Felienne commented
> Looking at the list of reserved words, I notice that it seems to cover language keywords but no (or few) function names. Is there some specific reason for not including those, or has it just not been an issue yet?

Yeah, just not something we thought about before! I am not sure we can find a nice list of all buildin functions? And also `t`! I notices a kid use `t` as a variable yesterday in class and that does not work cause we call the Turtle `t`!

2022-10-20 06:46 UTC, Felienne commented
Addendum: if we want to do it proper, we should exclude all of these: https://docs.python.org/3/library/functions.html

2022-10-20 21:26 UTC, JonathanMurray commented
> Addendum: if we want to do it proper, we should exclude all of these: https://docs.python.org/3/library/functions.html

Makes sense to me! It looks like in some cases we also call functions from modules (like `time.sleep` in the example above)? Not sure if that's a common case or not. There are definitely a lot of modules that _could_ be referenced in that case: https://docs.python.org/3/py-modindex.html

That makes me wonder if it's feasible to track them all beforehand, or if another possibility would be to detect during transpilation which names from the python stdlib that the code will use, and only at that point convert any variables that are clashing. (I haven't looked enough at the transpiler code yet to be able to tell if this is feasible.) A more defensive/lazy approach could be to simply convert all variables in a way that makes conflicts impossible (although I really liked how readable the transpiled code was, when looking under the hood!).

Is this an area where you might be interested in outsider contributions, or are there perhaps already some related plans/efforts?

2022-10-25 17:51 UTC, Felienne commented
> That makes me wonder if it's feasible to track them all beforehand, or if another possibility would be to detect during transpilation which names from the python stdlib that the code will use, and only at that point convert any variables that are clashing. 

Great question! I would say, if we exclude the whole list as linked, we already make the code better than we have it now (a gradual approach, haha!)

> (I haven't looked enough at the transpiler code yet to be able to tell if this is feasible.) A more defensive/lazy approach could be to simply convert all variables in a way that makes conflicts impossible (although I really liked how readable the transpiled code was, when looking under the hood!).

Indeed, the reasons we do not do that is to make the Python more readable (and make the variable dropdown nicer without any effort)

> Is this an area where you might be interested in outsider contributions, or are there perhaps already some related plans/efforts?

I don't think we have related efforts, so it would be great if you can pick it up (either in this PR or in a fresh one, whatever you prefer) Are you in Discord? That is typically the place where we discuss these types of things.

2022-10-31 10:28 UTC, Felienne requested changes
Let's do this proper and add all built-in functions, or at least the most common ones.

Do you want to pick this up further @JonathanMurray? Otherwise @jpelay can finish it?

2022-10-31 21:51 UTC, JonathanMurray commented
@Felienne (cc @jpelay) Hey, sorry for the slow reply. I added the list of function names from the 3.11.0 docs. I figured it might be nice for the future to see easily where different words originate from, so I decided to store them separately from the already existing list of keywords.

I agree a gradual approach seems reasonable here. Feel free to merge the PR if you think it makes sense in its current form.

2022-10-31 22:00 UTC, JonathanMurray commented
> And are you in Discord? That is typically the place where we discuss these types of things.

Yes! My username is Venom#1866. I don't normally use Discord much, but I took a peek inside the Hedy discord and noticed there are many channels. I'm guessing #developers would be the one for these sort of topics?

2022-11-01 10:49 UTC, Felienne commented
> @Felienne (cc @jpelay) Hey, sorry for the slow reply. I added the list of function names from the 3.11.0 docs. I figured it might be nice for the future to see easily where different words originate from, so I decided to store them separately from the already existing list of keywords.

Ah great idea to keep it separate!!

> I agree a gradual approach seems reasonable here. Feel free to merge the PR if you think it makes sense in its current form.

Will do!

2022-11-01 10:50 UTC, Felienne commented
> > And are you in Discord? That is typically the place where we discuss these types of things.
> 
> Yes! My username is Venom#1866. I don't normally use Discord much, but I took a peek inside the Hedy discord and noticed there are many channels. I'm guessing #developers would be the one for these sort of topics?

Ah good to know you are there too to chat! Yes #developers is the channel for discussions about code (although we are still figuring out what works best!)

2022-11-01 10:55 UTC, Felienne approved these changes
Yes this works!!

![image](https://user-images.githubusercontent.com/1003685/199217963-0052144c-284d-477c-a009-e7b29f4855f4.png)

2022-11-01 10:55 UTC, Felienne commented
Pasting the erroneous code here is case we need it ever again:
```
jump = 0
jumpTime = 1, 2, 3, 4, 5
for i in range 0 to 100
    if jump in jumpTime
        jump = jump - 1
        print 'Its jumping'
    else
        input = ask 'Jump?'
        if input = 'w'
            jump = 5
```

2022-11-01 10:56 UTC, merged