Fix Hebrew highlighting regex
hedyorg/hedy pull request #3500
Opened 2022-10-26 18:50 UTC by o11k

The regex `CHARACTER` from [highlighting/definition.py](https://github.com/Felienne/hedy/blob/main/highlighting/definition.py) now includes Hebrew characters. The editor no longer recognizes Hebrew characters as end-of-word.

Before (level 11):
![image](https://user-images.githubusercontent.com/61731312/198108602-c46e2f13-6628-4399-9fc8-0e238c673939.png)

After:
![image](https://user-images.githubusercontent.com/61731312/198108713-78d490ee-5b6b-4140-b3b3-4f2f9db55b3d.png)

2022-10-27 13:48 UTC, thjazi39 commented
I validate the modification that has been made to support the coloring of Hebrew characters. Maybe add some tests ?

2022-10-29 13:53 UTC, o11k commented
@Felienne You're right. `re` doesn't support Unicode categories, but the external `regex` does.
However, the pattern `[^\W\d_]` *almost* means "letter". More specifically, it matches characters from the following categories:
- Uppercase letter (Lu)
- Lowercase letter (Ll)
- Titlecase letter (Lt)
- Modifier letter (Lm)
- Other letter (Lo)
- Letter number (Nl)
- Other number (No)

Sadly, there are 686 characters from these categories, that this pattern doesn't match. All of them are very obscure, and most of them aren't even printable using Hedy's font.
https://gist.github.com/o11k/c646b5a09e3acee62f65e9c0c8cab773

There are basically 3 paths forward now:
1. Keep adding character ranges as needed - easy but a constant WIP
2. `[^\W\d_]` - my favorite :)
3. Use an external module like `regex` - also good.

2022-10-31 10:38 UTC, Felienne commented
Thanks for looking into this @o11k!!

> There are basically 3 paths forward now:
> 
> 1. Keep adding character ranges as needed - easy but a constant WIP
> 2. `[^\W\d_]` - my favorite :)
> 3. Use an external module like `regex` - also good.

I would prefer not 1 because that keeps showing buggy-looking code to users. I am totally ok with 2, what is the reason it is your favorite and do you see any downsides? If it matches a bit more like you say, that does not seem to be a problem to me, any other reasons we might not want that?

2022-10-31 10:39 UTC, Felienne requested changes
Ideally we fix this at once for all other non-Latin languages too!

2022-11-11 14:58 UTC, o11k commented
@Felienne How embarrassing... I missed some important details:

- `CHARACTER` includes numbers and an underscore, so we could have just replaced it with a `\w`, if not for the next fact.
- This regular expression is passed to the Ace editor, in Javascript (not Python). AFAIK, the only way to make Javascript match non-English letters and numbers, is to use the [Unicode flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode), which the Ace editor completely filters out. I tried it.

Unless we want to hack/fork/replace Ace, our best choice might be sticking to explicit character ranges...

2022-11-11 15:24 UTC, Felienne commented
> Unless we want to hack/fork/replace Ace, our best choice might be sticking to explicit character ranges...

Ah yes, now that you mention it, I know there was a reason we did not just do `\w`. Shall we then explicitly add "firstletter-lastletter" for our non-Latin langs, so that is (I think?)

Currently, I think: Thai, Bengali, Chinese, Farsi, Punjabi, Turkish, Russian, Ukranian, Greek (but maybe I forgot one, I used to be able to name all, but I lost count at one point haha!)

This might also requires diving into languages, f.e. do Russian and Ukranian share an alfabet? Turkish has a lot of Latin letters, but what extra's do they need etc...

I 100% understand if you do not want to fix this further @o11k! We can also pick it up if this is too much work for you, let us know (here or in Discord).

2022-11-11 15:42 UTC, jpelay commented
> * ludes numbers and an underscore, so we could have just replaced it wit



> @Felienne How embarrassing... I missed some important details:
> 
>     * `CHARACTER` includes numbers and an underscore, so we could have just replaced it with a `\w`, if not for the next fact.
> 
>     * This regular expression is passed to the Ace editor, in Javascript (not Python). AFAIK, the only way to make Javascript match non-English letters and numbers, is to use the [Unicode flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode), which the Ace editor completely filters out. I tried it.
> 
> 
> Unless we want to hack/fork/replace Ace, our best choice might be sticking to explicit character ranges...

Yes, we're in the same place right now. I was just trying this, and the ACE editor filters the u flag!

2022-11-17 21:52 UTC, jpelay commented
@Felienne I solved the problem by doing a few things:

1. Changing the `CHARACTER` regex to the one used in the grammars.
2. Changing the regex library used in the highlighter module from`re` to `regex`, because `regex` does accept unicode categories.
3. Updating ace.js to the last version.
4. Adding the `unicode: true` attribute to all the rules in the highlighter, this will tell ace that it needs to add the unicode flag to the regexes.

The code in the issue now looks like this:
![image](https://user-images.githubusercontent.com/45865185/202567191-535c8773-4964-472c-bd22-8efd254088c5.png)

And the one in level 11 looks like this:
![image](https://user-images.githubusercontent.com/45865185/202567322-ef473ce6-1305-4232-b200-812dee4c13df.png)

2022-11-18 17:30 UTC, o11k commented
It works! This is probably the best solution. Thank you @jpelay !

2022-11-21 20:05 UTC, Felienne approved these changes
Just checked it and yes it works for Hebrew and also for other langs like Chinese: 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/1003685/203148126-004a0f74-526f-4ab0-884f-a2ac0f684d53.png">

2022-11-21 20:12 UTC, jpelay commented on requirements.txt
> +pre-commit==2.20.0
No it isn't intentional!

2022-11-21 20:13 UTC, jpelay commented on requirements.txt
> +pre-commit==2.20.0
Hi! No it wasn't, but notice that I reverted that change and won't be committed!

2022-11-21 20:21 UTC, merged