[TESTING] 3624 tests for logs and class statistics button in class page
hedyorg/hedy pull request #3627
Opened 2022-11-10 15:57 UTC by hanna1231

**Description**
With this test the logs and class statistics button in the `/for-teachers/class/[class id]` page. This test will also navigate to the `/logs/class/[class id]` and `/stats/class/[class id]` and therefore this tests can be used for other front-tests.

**Fixes _issue or discussion number_**
Fixes #3624 

**How to test**
Run 
`export ADMIN_USER=admin_user; python app.py` in your virtual environment. This ensures that there is an active admin_user and Hedy is running.

Then you can go to the /tests folder and run: 

`npx cypress run --spec cypress/e2e/teacher_page/class_page`

2022-11-10 16:38 UTC, TiBiBa commented on tests/cypress/e2e/teacher_page/class_page/logs_button.cy.js
> +      let logsButton = `[onclick="window.location.href = '/logs/class/` + currentUrl.substring(currentUrl.indexOf('class/')+6) + `'"]`; // Get logs button
Same here, what is we decide to change the url of the class? Is there a way to make this more flexible as well?

2022-11-14 13:55 UTC, hanna1231 commented on tests/cypress/e2e/teacher_page/class_page/logs_button.cy.js
> +    cy.get(":nth-child(1) > :nth-child(3) > .no-underline").click(); // Press view class button
I am not sure if this is something that I can make more flexible. If I for example would select buttons by using the text on it then it wouldn't work for other languages. I will have another look at it to see if I can find a solution but I saw that there was already a PR approved that also uses this method of selecting buttons.

2022-11-14 15:16 UTC, hanna1231 commented
I created id's to make selecting the buttons more flexible. I will also try to find a similar solution to making the url's more flexible

2022-11-16 13:00 UTC, TiBiBa requested changes
Running the tests seem to fail on the following issue :
```
 AssertionError: Timed out retrying after 4000ms: Expected to find element: `#teacher_classes > .green-btn`, but never found it.
```

I would propose to change this structure to adding an id to the "create class" button and calling it directly. Not sure if this would solve the issue, but would be a bit more flexible for future UI changes (adding buttons to the for-teachers page for example).

2022-11-17 10:41 UTC, hanna1231 commented
> 

I did not get this error myself which is strange but I followed your suggestion and hopefully it works now!

2022-11-17 12:52 UTC, TiBiBa approved these changes
All works, good job!

2022-11-17 13:07 UTC, merged