[TESTING] 3562 part of classpage, add student by link and username
hedyorg/hedy pull request #3682
Opened 2022-11-21 15:19 UTC by ElyanneOey

[TESTING, CYPRESS]

**Description**
Adds cypress front end tests for features on the `/for-teacher/class/[class id]` page. One test checks if the link to add a student to the class is copied to the clipboard. And the other tests checks if a student is added when you add a student by username. I tried to implemented in a dynamic fashion.

**Fixes _issue or discussion number_**
Fixes #3562

**How to test**

Run
`export ADMIN_USER=admin_user; python app.py` in your virtual environment. This ensures that there is an active admin_user and Hedy is running.

Then you can go to the /tests folder and run:

`npx cypress run --spec cypress/e2e/teacher_page/class_page`

2022-11-22 12:19 UTC, Felienne requested changes

2022-11-22 12:19 UTC, Felienne commented on tests/cypress/e2e/teacher_page/class_page/add_student_copy_link.cy.js
> +    cy.get('.green-btn').contains("Add students").click();
This will only work when the site is set to English, can you make it more generic?

2022-11-22 12:26 UTC, Felienne commented
And even with the language set to English, I seem to be getting failing specs:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1003685/203313621-0310a1d2-a64c-4895-a43f-959c05e97048.png">

Details on one:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1003685/203313595-d348f16c-30dd-43dd-b5de-9f32a008521b.png">

2022-12-09 10:29 UTC, TiBiBa requested changes
I can't seem to run this? Is something changed?
![Schermafbeelding 2022-12-09 om 11 28 54](https://user-images.githubusercontent.com/38155424/206681887-a28187a3-4064-4910-85a6-ab00de981107.png)

2022-12-11 13:41 UTC, ElyanneOey commented
Sorry the tests are in a different folder. I changed the pull request. `npx cypress run --spec cypress/e2e/for-teacher_page/class_page`. This should be run.

2022-12-11 15:17 UTC, TiBiBa commented
It does have some merge conflicts now. Can you fix these? I will review your PR!

2022-12-11 15:24 UTC, TiBiBa submitted a review, later dismissed
Left quite some comments, but most should be easy to fix. Let me know if you need any help!

2022-12-11 19:05 UTC, ElyanneOey commented
I fixed the merge conflict and made the changes.

2022-12-11 19:58 UTC, ElyanneOey commented
I made a change to the add_student_invite_by_username file. And it should pass the test now. However I don't understand why the test 'add_student_copy_link' fails. In the test it does click on the 'copy_join_link' button. And on the screen the message: 'Join link successfully copied to clipboard' does appear. But the link is actually not copied to the clipboard. That is why it fails. But when I click on the 'copy_join_link' button the link is copied to the clipboard. I don't understand why it works when I press the button but not when the test is run. Do you have any ideas?

2022-12-15 14:43 UTC, ElyanneOey commented
I do not understand why the test add_student_invite_by_username fails. When I run it locally it does work. Could you maybe take a look? Also the class is coming to its end, and I am not sure how much I will be able to work on the test.

2022-12-15 15:27 UTC, Felienne commented
> I do not understand why the test add_student_invite_by_username fails. When I run it locally it does work. Could you maybe take a look? Also the class is coming to its end, and I am not sure how much I will be able to work on the test.

It is probably due to differences in test data. Can you delete your local db and copy it afresh?

2023-01-02 14:08 UTC, Felienne commented
I took a look but I am unable to find out why this fails (it was not test data, I verified that) 

Will just delete the one failing test so we can move on.

2023-01-03 08:29 UTC, Felienne approved these changes

2023-01-03 09:05 UTC, merged