[FIX] added support for adding/removing numbers and list accesses to/from lists (#3293)
hedyorg/hedy pull request #3685
Opened 2022-11-21 20:11 UTC by jakeklaris

[FIX] added support for adding/removing numbers and list accesses to/from lists (#3293)

**Description**

Adds support to levels 3+ for adding integers or floats to lists, and removing integers of floats from lists. Also fixes the issue where accessing a list item with square bracket indexing gets changed into a literal string when adding or removing from a list (ex. add list1[2] to list2, appends 'list1[2]' as a string to list2)

**Fixes Issue #3293**

**How to test**

Adds a test to test_level_03.py for checking that a number can be added to a list
Adds tests to test_level_16.py for checking that square bracket list indexing correctly gets added and removed from a list

2022-11-21 20:18 UTC, Felienne commented
Welcome to Hedy @jakeklaris and well done on picking up a language bug as your first PR! We can simplify the code a bit but it does seem to work (leaving a few details comments now)

2022-11-21 20:19 UTC, Felienne commented on hedy.py
> +        if args[0].isnumeric(): # is int/float
Would be good to repeat the comment from add here (future readers will not always think to read add when looking for more info on remove)
```suggestion
      # only process arg if arg is a string, else keep as is (ie. don't change 5 into '5', my_list[1] into 'my_list[1]')
        if args[0].isnumeric(): # is int/float
```

2022-11-21 20:21 UTC, Felienne commented on hedy.py
> +            value = self.process_variable(args[0], meta.line)
These lines are exactly the same as for add, can we make a function for this and call it from both places (a bit like arithmetic operators do in level 6 by all calling `process_calculation()`)

2022-11-21 20:22 UTC, Felienne requested changes
These are all supersmall style tips, the mechanic seems to work just fine!

2022-11-21 22:12 UTC, jakeklaris commented
> These are all supersmall style tips, the mechanic seems to work just fine!

Great! Just updated the code to account for the style tips. Let me know what you think.

2022-11-22 11:42 UTC, Felienne approved these changes
Thanks for the fixes, and congrats on getting your first PR merged @jakeklaris!

2022-11-22 12:00 UTC, merged