[REFACTOR] Clearly distinguish prod and development css
hedyorg/hedy pull request #4148
Opened 2023-03-18 15:25 UTC by rix0rrr

After the discussion in #4102 and #4130, I will try to clean up the mess I made!

Here is the new situation:

* We now have two different scripts, `generate-prod-css` and `generate-development-css`.
* These generate into two different files, `generated.full.css` and `generated.css`.
* Depending on whether we are in debug mode or not, the right file is referenced in the HTML.

Hopefully, this will get rid of all the confusion surrounding the purpose of these files!

@TiBiBa, @reedspool, what do you think?

2023-03-18 15:26 UTC, rix0rrr commented
Here's another thought: we can potentially NOT minify the files that get committed to version control, to reduce the chances of merge conflicts in them!

2023-03-19 12:14 UTC, TiBiBa commented
> Here's another thought: we can potentially NOT minify the files that get committed to version control, to reduce the chances of merge conflicts in them!

Would love this! Not minifying the development version makes it easier to understand for new contributors as well, with the addition that CSS changes in a PR can be clearly distinguished in the file.

2023-03-20 07:43 UTC, Felienne requested changes
Setting this to changes requires for the not minifying (otherwise it is too hard for me to keep track of the PRs)

2023-03-21 06:48 UTC, reedspool commented
Nice! Could consider `.gitignore` for the deployment CSS now.

This definitely feels like a great step especially and much more informative docs!

2023-03-21 09:08 UTC, rix0rrr commented on CONTRIBUTING.md
> +* Want to use a *conditional* Tailwind class (for example, a class that starts with `hover:`).
```suggestion
* Use a *conditional* Tailwind class (for example, a class that starts with `hover:`).
```

2023-03-21 17:38 UTC, Felienne commented
> LGTM!

Do you have enough rights to officially approve the PR? You have my blessing to do so!

2023-03-21 17:40 UTC, reedspool commented
I do not see a button to do so

2023-03-21 18:44 UTC, merged