[DRAFT] Implement a dedicated embedding route
hedyorg/hedy pull request #4615
Opened 2023-10-10 12:44 UTC by TiBiBa

Start the name of the PR with one of the relevant prefixed in the title of the PR:

* [LANGUAGE] -> changes related to grammars or the transpiler
* [FIX] -> solving a bug
* [CHORE] -> things unrelated to the code, such as mergify scripts
* [REFACTORING] -> should not change anything, cleanup of code
* [UI] -> improvements and changes of the Hedy user interface
* [TESTING] -> changes made to the test suite
* [BACKEND] -> changes to the internal logic of the Hedy website

Finish the name of the PR with a clear description of the changes and delete the lines above from the description.

**Now fill out the remainder of this template by replacing all _italic_ content**

**Description**

_Changes in detail. For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present tense!)_

**Fixes _issue or discussion number_**

Always link the number of the issue or of the discussion that your PR concerns.
Tip, if you use the word `fixes` before the issue number in this description, the related issue will automatically close then the PR is merged!

**How to test**

* If this is a UI change: _describe how to run your code to see it in action. See this https://github.com/hedyorg/hedy/pull/880#issue-1016304308 for an example_
* If this is a language change: _add a few tests showing the difference_

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [ ] Contains one of the PR categories in the name
- [ ] Describes changes in the format above
- [ ] Links to an existing issue or discussion
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

2023-10-10 17:56 UTC, TiBiBa commented
On seconds thoughts I think it would be wise to create a completely separate code editor. This makes us more flexible and doesn't make it hard to read with the raw, embedded and admin exceptions build within the templates. I will further look into this tomorrow.

2023-10-16 13:44 UTC, jpelay commented
Hi, Timon! The title says draft but you marked the PR as open, is this PR ready for review?

2023-10-16 13:46 UTC, TiBiBa commented
> Hi, Timon! The title says draft but you marked the PR as open, is this PR ready for review?

My bad! It is indeed ready for review, will change the title.

2023-10-16 13:47 UTC, jpelay commented
> My bad! It is indeed ready for review, will change the title.

Thanks, no problem :D

2023-10-17 08:26 UTC, TiBiBa commented
Note to self: We should force logout the user when including the embedded editor to prevent possible undesirable behavior when logged in and also using the embedded editor in another spot.

2023-10-17 13:15 UTC, jpelay requested changes
Hi, @TiBiBa! I think this is a great idea. A while ago a teaching organization here in Venezuela was interested in a Hedy course, but they wanted to be able to just use the language and not the teacher features. This is a great step in that direction and a great PR! 

I just left a couple of comments because I think perhaps defaulting to NL is not what we usually do in other parts of the system. Also a following question, can you provide me a URL with a example of how can I test running a program?  And also, if I try execute a program with `ask`, the turtle or `pressit` will the host page be able to somehow catch and show those changes?

2023-10-17 13:15 UTC, jpelay commented on app.py
> +            program = '# Gekozen leven is ongeldig, Hedy staat nu op level 1'
Should we try to make this a translatable message? Perhaps instead of a comment we can show an alert message to the user somehow? What do you think?

2023-10-17 14:51 UTC, TiBiBa commented on app.py
> +    language = request.args.get('lang', 'nl')
Agree, this should fallback to English!

2023-10-17 14:55 UTC, TiBiBa commented
> Hi, @TiBiBa! I think this is a great idea. A while ago a teaching organization here in Venezuela was interested in a Hedy course, but they wanted to be able to just use the language and not the teacher features. This is a great step in that direction and a great PR!
> 
> I just left a couple of comments because I think perhaps defaulting to NL is not what we usually do in other parts of the system. Also a following question, can you provide me a URL with a example of how can I test running a program? And also, if I try execute a program with `ask`, the turtle or `pressit` will the host page be able to somehow catch and show those changes?

I don't understand what you mean with catching and showing these changes? I've implement two event triggers for which the host page can listen: an editor change an a run event. I thought this would be sufficient for any host page to work with possible changes.

2023-10-18 22:00 UTC, jpelay approved these changes
Works great!!! Thanks for explaining yesterday the use case, that made much clearer the intended change!

2023-10-18 22:19 UTC, merged