second teacher
hedyorg/hedy pull request #4644
Opened 2023-10-19 02:49 UTC by hasan-sh

- add is_second_teacher to global context #3610
- allow generic invitations. #3610
- show second teachers in class overview #3610
- a second teacher is a teacher as well #3610
- WIP: allow second teachers in /for-teachers #3610
- show messages, if any, by default
- use htmx instead of redirecting to join-link #3610
- util for adding pending achievements #3610
- minor logic for second teachers #3610
- nav items visible to second teachers as well
- generalizing the logic of pending achievements event
- autopep8
- WIP: join class immeadiately #3610
- WIP: legacy joining class adjustments #3610
- DELETE a second teacher #3610
- invite a second teacher #3610
- show second teachers and their roles in pending invite #3610

Start the name of the PR with one of the relevant prefixed in the title of the PR:

* [LANGUAGE] -> changes related to grammars or the transpiler
* [FIX] -> solving a bug
* [CHORE] -> things unrelated to the code, such as mergify scripts
* [REFACTORING] -> should not change anything, cleanup of code
* [UI] -> improvements and changes of the Hedy user interface
* [TESTING] -> changes made to the test suite
* [BACKEND] -> changes to the internal logic of the Hedy website

Finish the name of the PR with a clear description of the changes and delete the lines above from the description.

**Now fill out the remainder of this template by replacing all _italic_ content**

**Description**

_Changes in detail. For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present tense!)_

**Fixes _issue or discussion number_**

Always link the number of the issue or of the discussion that your PR concerns.
Tip, if you use the word `fixes` before the issue number in this description, the related issue will automatically close then the PR is merged!

**How to test**

* If this is a UI change: _describe how to run your code to see it in action. See this https://github.com/hedyorg/hedy/pull/880#issue-1016304308 for an example_
* If this is a language change: _add a few tests showing the difference_

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [ ] Contains one of the PR categories in the name
- [ ] Describes changes in the format above
- [ ] Links to an existing issue or discussion
- [ ] Has a "How to test" section

If you're unsure about any of these, don't hesitate to ask. We're here to help!

2023-10-27 12:00 UTC, Felienne commented on content/adventures/en.yaml
>                      ```
Hmmm these changes are going to upset weblate probably, but also... why are they in this PR? These seem uprelated? I don't know how they got here, do you understand @hasan-sh?

2023-10-27 12:01 UTC, Felienne commented on content/adventures/en.yaml
>                      ```
(maybe a merge from main when the conflicts are addressed will solve this?)

2023-10-27 12:02 UTC, Felienne commented on README.md
> +<div id="top"></div>
This too is a recent change on main, and as fas as I understand should not be here.

2023-10-30 15:58 UTC, Felienne commented
I have correctly merged main in @hasan-sh! I set it to draft because it is now missing your new strings and translations. 

Can you add those by running extract again? (if not no problem, than I will finish it later)

2023-10-30 20:07 UTC, hasan-sh commented
> Can you re-add them?

Sure, will do so tomorrow morning ;)

2023-10-31 08:42 UTC, Felienne requested changes
Hi @hasan-sh!

I tried the feature and it works great!! Teachers will be very happy!

I love also how you have thought of many details, like adding the role in the invite list:

<img width="798" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/876004ae-f86d-4d81-bef8-96ffb89538cf">

There are still a few tests failing, hope you can look into those! 

In addition to that, a few comments from my first trial run.

* I am not sure if I am supposed to type a username or email address here? Or maybe both work? Can we add a label?
<img width="796" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/746e9893-2212-4671-957c-cf8314085881">

* inviting a non-existing teacher gives a weird error:
<img width="822" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/1c60cb9d-6f7a-4029-b7c0-e8b5574a5b56">

* this is a bit of a "stretch goal" (let's do that in a separate PR!) but maybe we want to show the teachers here too: 
<img width="1165" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/ffc943ac-36bd-4ac2-9ad1-474286753d4d">
 
* this too is a nice to have, but maybe after the adventure name here we can also add the author (maybe between brackets?) 
<img width="274" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/8f568506-ca3c-4d1f-b9b4-d59373d82538">

* I was not sure what this label is:
<img width="240" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/7851c98c-33df-4a99-bc5d-11ad68e4bc97">
 (but maybe I'd understand if the strings are filled)

2023-11-01 07:51 UTC, Felienne commented
Hi @hasan-sh! I think in principle, this is good to go (it seems to work well) but we need to look at the tests, do they catch a real problem, are they breaking for no reason (that sometimes happens) or are they in need of some changes due to the PR?

Let us know if you need help fixing the tests!

2023-11-01 12:28 UTC, hasan-sh commented
> Hi @hasan-sh! I think in principle, this is good to go (it seems to work well) but we need to look at the tests, do they catch a real problem, are they breaking for no reason (that sometimes happens) or are they in need of some changes due to the PR?
> 
> Let us know if you need help fixing the tests!

I changed my approach on testing the feature; some tests relied on others. Now they run independenlty! All tests passed locally! However, the error that the github action yields is: `Os is not defined`. I think it's some missing env variable or some other small thing!

2023-11-01 12:41 UTC, Felienne commented
> > Hi @hasan-sh! I think in principle, this is good to go (it seems to work well) but we need to look at the tests, do they catch a real problem, are they breaking for no reason (that sometimes happens) or are they in need of some changes due to the PR?
> > Let us know if you need help fixing the tests!
> 
> I changed my approach on testing the feature; some tests relied on others. Now they run independenlty! All tests passed locally! However, the error that the github action yields is: `Os is not defined`. I think it's some missing env variable or some other small thing!

For me also the e2e tests pass locally (I dud not try Cypress) so indeed I guess something small/weird is amiss, but we still need to see how to get this fixed since we don't want to merge broken tests. I don't know what the issue is myself.

Do have time to dive in and do you see a path forward? Because of all the changes and commits it is very hard for someone else to understand what happens (or maybe @jpelay has a brilliant plan?)

2023-11-01 12:53 UTC, hasan-sh commented
> Do have time to dive in and do you see a path forward? Because of all the changes and commits it is very hard for someone else to understand what happens (or maybe @jpelay has a brilliant plan?)

Yes, I do. Just pushed the tests for adding tags to adventures! Will look into this!

2023-11-02 05:44 UTC, Felienne commented
Woohoo, all good to go! I will do Weblate first and then this one.

2023-11-02 05:44 UTC, Felienne approved these changes

2023-11-02 07:45 UTC, merged