[UI] Switch read only editors to code mirror
hedyorg/hedy pull request #4924
Opened 2023-12-18 23:38 UTC by jpelay

**Description**

Changes the read-only editors to use CodeMirror

2023-12-22 21:03 UTC, jpelay commented
Should I remove all of the code related to Ace too?

2023-12-29 10:12 UTC, Felienne requested changes
Looks great @jpelay!

Just a small thing, a one line editor gets a scroll bar now (macOS, Chrome):

<img width="788" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/7397b024-300b-4c24-9c56-bd4c9b38cb53">

While this is not the case in the current main:
<img width="760" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/5ee7c5f3-2b87-4f2c-ab86-f96043e4fd2e">

Since it is the first code block in the first level, it looks a bit sloppy if we leve it like this, so can you see if you can fix that?

And I'd also like a sanity check on the ts from @hasan-sh because I only skimmed it!

2023-12-29 10:12 UTC, Felienne commented on static/js/parsons.ts
> +export function initializeParsons() {
Really nice clean up of the Parson's code!

2023-12-29 10:12 UTC, Felienne commented on templates/incl/editor-and-output.html
> -// FIXME: Stop using inline JavaScript
Haha, partly addressed with this PR? ;)

2023-12-29 13:31 UTC, jpelay commented
> Looks great @jpelay!
> 
> Just a small thing, a one line editor gets a scroll bar now (macOS, Chrome):
> 
> <img alt="image" width="788" src="https://private-user-images.githubusercontent.com/1003685/293344703-7397b024-300b-4c24-9c56-bd4c9b38cb53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTY5MzAsIm5iZiI6MTcwMzg1NjYzMCwicGF0aCI6Ii8xMDAzNjg1LzI5MzM0NDcwMy03Mzk3YjAyNC0zMDBiLTRjMjQtOWM1Ni1iZDRjOWIzOGNiNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTMzMDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzRkYzNiYTQyNDY1NmE1ODg5MDQ4YTEzYzEyOGNkZWM1MjdmNDQ2ZjRlNDM0ZWI3NDcxZWU4OGE1NzE4ZDc2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WBRUv56hH_CrDYU9wBC7Dy3M4m-g-rI0MJ4kY9hJu4g">
> While this is not the case in the current main: <img alt="image" width="760" src="https://private-user-images.githubusercontent.com/1003685/293344738-5ee7c5f3-2b87-4f2c-ab86-f96043e4fd2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTY5MzAsIm5iZiI6MTcwMzg1NjYzMCwicGF0aCI6Ii8xMDAzNjg1LzI5MzM0NDczOC01ZWU3YzVmMy0yYjg3LTRmMmMtYWI4Ni1mOTYwNDNlNGZkMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTMzMDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE0NjljNWYyMjE0MTY4ZmE1ZWI1NTFlZTJiYTM0MzYwMTlmY2E4YjA3YzYxYzlmZjgzYmM5MjFmYWY5ZjYyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dTjJd3Wb65RWji01XIGGnbq6OgXfxlTug0277kjuLag">


Good catch! I'll fix it!

2024-01-02 16:05 UTC, Felienne approved these changes
Looks great now!

![Uploading image.png…]()

2024-01-02 16:12 UTC, Felienne commented
@jpelay Do you think we need to open an issue to remind ourselves to remove Ace code? (f.e. the highlighter code that I changed in #4903)

2024-01-02 16:22 UTC, jpelay commented
> @jpelay Do you think we need to open an issue to remind ourselves to remove Ace code? (f.e. the highlighter code that I changed in #4903)

Yes, opened #4941 for that matter!

2024-01-02 16:41 UTC, merged