Allowing unsetting of favourite program
hedyorg/hedy pull request #5151
Opened 2024-02-14 13:23 UTC by TiBiBa

This PR fixes #5132

2024-03-19 11:00 UTC, Felienne commented
Hi @hasan-sh!

This is a somewhat longstanding R, could you pick it up? I am not sure how ready it is but I think it can be a small PR in between other things.

2024-03-19 11:31 UTC, hasan-sh commented
> Hi @hasan-sh!
> 
> This is a somewhat longstanding R, could you pick it up? I am not sure how ready it is but I think it can be a small PR in between other things.

Will do so after the autosave PR. I'm also investigating the login problems that we discussed with the teachers!

2024-03-28 11:09 UTC, hasan-sh requested changes
I cannot favourite a program without a refresh. I'll review the code once this is done! Let me know if you need any help:)

2024-04-02 14:48 UTC, Annelein commented
@hasan-sh all tests have passed, ready to be reviewed again, only needs to wait for that issue right?

2024-04-03 13:27 UTC, Annelein commented
@hasan-sh I've also added a test for favouriting and unfavouriting a program as mentioned in #4251, can you let me know if this is how a test is supposed to be?

2024-04-03 13:54 UTC, hasan-sh commented
Great @Annelein , will review your PR

2024-04-04 13:28 UTC, hasan-sh requested changes
Hi, i remember making it possible to update the UI from TS; https://github.com/hedyorg/hedy/commit/ffa813a5ee9788ea81607dceff828125e298ad58#diff-810bc5b30fefd1c7d50d825f1331efb7cda58a958fdbe93d015904aed1735a47R29-R35


Why did you move the data-starred attribute to the i element instead of the container? Now you the ui isn't updating as it was! 

I suggested a change that fixes the issue, but do take a look at the test and whether anything else depends on what i changed!

2024-04-04 13:28 UTC, hasan-sh commented on templates/htmx-program.html
> +                    data-starred="{{favourite_program}}"
This should fix it!

```suggestion
            <div
                id="favourite_program_container_{{ program.id }}"
                data-starred="{{favourite_program}}"
                class="ml-auto favourite_program_container {% if favourite_program %}text-yellow-400{% else %}text-white{% endif %} text-2xl{% if not program.public %} hidden{% endif %}">
                <i class="fa fa-star p-4 bg-blue-300 rounded-full cursor-pointer hover:bg-blue-600"
```

2024-04-08 07:32 UTC, Annelein commented
> Hi, i remember making it possible to update the UI from TS; [ffa813a#diff-810bc5b30fefd1c7d50d825f1331efb7cda58a958fdbe93d015904aed1735a47R29-R35](https://github.com/hedyorg/hedy/commit/ffa813a5ee9788ea81607dceff828125e298ad58#diff-810bc5b30fefd1c7d50d825f1331efb7cda58a958fdbe93d015904aed1735a47R29-R35)
> 
> Why did you move the data-starred attribute to the i element instead of the container? Now you the ui isn't updating as it was!

I did this because the test was failing because it would miss click because this is the space the container takes up, so now the test fails again:
<img width="951" alt="Screenshot 2024-04-08 at 09 31 38" src="https://github.com/hedyorg/hedy/assets/48122190/b8b6b012-2717-4b3b-b177-b7dbf48c5f55">

2024-04-08 14:10 UTC, hasan-sh commented
@Annelein the `set_favourite_program` uses need to be fixed. Try to make a program private after favouriting it.

2024-04-09 14:08 UTC, hasan-sh approved these changes

2024-04-09 14:39 UTC, merged