💻 hide all quizes/parsons and show tabs in levels
hedyorg/hedy pull request #5156
Opened 2024-02-15 15:55 UTC by hasan-sh

- add quiz and parsons to default adventures
- indicate special tab for quiz and parsons
- remove all existing quizes or puzzles tabs if user wanted to hide them all
- remove hide_quiz or hide_parsons if user wants to add one quiz or parsons to levels
- add quiz nd parsons to default advs if they are shown
- what to do for existing classes?!

2024-03-06 16:38 UTC, jpelay requested changes
Hi @hasan-sh! Sorry for not reviewing it earlier! Everything works great, and I think this is a great idea, however there's something we must change: if a class already has a customization object and I enter the customization page again, then my class won't have any quizes. Can we find a way to automatically add parsons and quizzes to the customization objects that hasn't been touched previous to this PR? Like a migration.

2024-03-07 11:50 UTC, hasan-sh commented
> Hi @hasan-sh! Sorry for not reviewing it earlier! Everything works great, and I think this is a great idea, however there's something we must change: if a class already has a customization object and I enter the customization page again, then my class won't have any quizes. Can we find a way to automatically add parsons and quizzes to the customization objects that hasn't been touched previous to this PR? Like a migration.

@jpelay thanks for the reminder, i had a TODO in the code, but apparently i missed it! Does your IDE notify you about todos!?

Now it should be ready to roll!

2024-03-07 13:37 UTC, jpelay approved these changes

2024-03-07 13:37 UTC, merged

2024-03-07 13:37 UTC, jpelay commented
> @jpelay thanks for the reminder, i had a TODO in the code, but apparently i missed it! Does your IDE notify you about todos!?
> 
> Now it should be ready to roll!

Actually no haha! I often write those down in my notebook or in the calender. If I do it in the code I tend to forget.