💻 Check for underscore in variable, remove it
hedyorg/hedy pull request #5324
Opened 2024-03-27 13:13 UTC by Annelein

Fixes #4749 

**How to test**
1. Add for example this code:
```
continue = ask 'Do you want to continue?'
if continue is yes
    sure = ask 'Are you sure?'
    if sure = yes
        print 'We will continue'
    else
        print 'You are not sure'
else
    print 'You do not want to conintinue'
```

2. none of the variables should have an underscore:
<img width="209" alt="Screenshot 2024-03-27 at 14 13 04" src="https://github.com/hedyorg/hedy/assets/48122190/20a8e25e-a100-4ecc-b973-7776b3c230c0">

2024-03-28 11:19 UTC, boryanagoncharenko requested changes

2024-03-28 11:19 UTC, boryanagoncharenko commented on static/js/debugging.ts
> +        const variableName = variables[i][0].replace('_', '');
I think we need to get rid of underscores if they appear in the beginning of the variable name. With the current approach, we remove the first underscore even when it is in the middle of the variable name, which is incorrect:
<img width="762" alt="Screenshot 2024-03-28 at 13 07 54" src="https://github.com/hedyorg/hedy/assets/3010723/1b5f3d43-176b-4e96-92d8-cff15f387440">

2024-03-28 12:47 UTC, Felienne commented
Hi @Annelein!

I think the variable is still not showing correctly:

<img width="1384" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/40870776-d9f9-465e-a64b-01325fb5ea9e">

Also, can we remove the underscore in the yellow warning bar too?

2024-03-28 13:07 UTC, Annelein commented
> Hi @Annelein!
> 
> I think the variable is still not showing correctly:
> 
> <img alt="image" width="1384" src="https://private-user-images.githubusercontent.com/1003685/317729940-40870776-d9f9-465e-a64b-01325fb5ea9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzE1MzEsIm5iZiI6MTcxMTYzMTIzMSwicGF0aCI6Ii8xMDAzNjg1LzMxNzcyOTk0MC00MDg3MDc3Ni1kOWY5LTQ2NWUtYTY0Yi0wMTMyNWZiNWVhOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTMwNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQxZjc4Yzc1ZDM2YzgyZmRhZjA2YzE4NGYxNTdkOTJhMjU4ZmMwYmE1OGE3MmRmNjEyNDA1YWE2ODVkZjQ2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7xR5nGyvJRAZTN0BjuP7IN8QI1y8NM4JV4BmCeyrETo">
> Also, can we remove the underscore in the yellow warning bar too?

Oh that's weird! It worked for me.. Will look into it.

2024-03-28 13:15 UTC, Annelein commented
@Felienne does it work now?

2024-03-28 15:12 UTC, boryanagoncharenko requested changes

2024-03-28 15:12 UTC, boryanagoncharenko commented on static/js/debugging.ts
> +        console.log("HAAI")
Perhaps this is committed by accident? Could you please remove this line? Otherwise, it looks great.

2024-03-29 11:11 UTC, boryanagoncharenko approved these changes

2024-03-29 11:40 UTC, merged