🧹 Remove duplication in snippet testing
hedyorg/hedy pull request #5345
Opened 2024-04-01 11:15 UTC by rix0rrr

The snippet testing code had a lot of duplicated code; the differences were in locating snippets in YAML files, and then again to reset sections of a YAML file to English if the code doesn't compile.

For every snippet, we can remember where in a YAML file we found it (by keeping track of the keys we used to descend into dictionaries and the indexes we used to descend into lists), so the "restore to English" code becomes generic; finding and iterating YAML is also generic,. The only thing that's left is indicating where in the YAML we can find interesting snippets.

We now do that by talking about the path in string form, in the best case using a map. It now looks like this:

```python
snippets = snippet_tester.collect_yaml_snippets('content/adventures', {
    # the default tab sometimes contains broken code to make a point to learners about changing syntax.
    'adventures.default': snippet_tester.SKIP,
    'adventures.debugging': snippet_tester.SKIP,
    'adventures.*.levels.<LEVEL>.story_text*': snippet_tester.COLLECT_MARKDOWN,
    'adventures.*.levels.<LEVEL>.example_code*': snippet_tester.COLLECT_MARKDOWN,
})

snippets = snippet_tester.collect_yaml_snippets('content/cheatsheets', {
    '<LEVEL>.demo_code': snippet_tester.COLLECT,
})

snippets = snippet_tester.collect_yaml_snippets('content/parsons', {
    'levels.<LEVEL>.*.code': snippet_tester.COLLECT,
})
```

The "slides" locator is more complex because the skipping behavior is triggered off of another field of a containing object, instead of the path:

```python
def slides_locator(entry):
    """Locator for snippets in the slides YAML.

    More complicated than the regular locators.
    """
    if isinstance(entry.value, dict) and entry.value.get('debug'):
        # Some entries are designed to fail, skip those
        return snippet_tester.SKIP

    return at_least_level_1(snippet_tester.locator_decision_from_map(entry.field_path, {
        'levels.<LEVEL>.*.code': snippet_tester.COLLECT,
    }))
```

**How to test**

If the tests pass, everything works!

2024-04-03 14:14 UTC, boryanagoncharenko requested changes

2024-04-03 14:14 UTC, boryanagoncharenko commented on tests/test_snippets/snippet_tester.py
> +        original_loc = locate_snippet_in_yaml(original_yaml, snippet, yaml_locator)
The `yaml_locator` does not need to be supplied any more

2024-04-03 14:14 UTC, boryanagoncharenko commented on tests/test_snippets/snippet_tester.py
>  - Snippets can hold on to the information where in the YAML file they were
This could be scratched now, right :)

2024-04-04 08:59 UTC, rix0rrr commented on tests/test_snippets/snippet_tester.py
> +        snippets = [s for s in snippets if x.language[:len(lang)] == lang]
Oops!

2024-04-04 09:00 UTC, rix0rrr commented on tests/test_snippets/snippet_tester.py
> +        snippets = [s for s in snippets if x.language[:len(lang)] == lang]
Tiens. I thought `pylint` would catch errors like these.

2024-04-04 09:02 UTC, rix0rrr commented
Good catches @boryanagoncharenko, thanks! I'm a bit surprised that the static analysis tools we run didn't catch these, since they're pretty obvious. 

I've confirmed that `pylint` doesn't catch them (grr). `pylance` could potentially do it, but I didn't find out how to run it.

We should probably find a static checker to catch trivial errors?

2024-04-04 09:03 UTC, rix0rrr commented on tests/test_snippets/snippet_tester.py
>  - Snippets can hold on to the information where in the YAML file they were
Ha. Of course!

2024-04-04 09:23 UTC, rix0rrr commented
I've re-added `pylint` to the build checks, and confirmed that `pylint` would have caught those errors.

We used to have it, not sure why we removed it?

2024-04-04 09:29 UTC, rix0rrr commented
Shit, pylint was removed in this PR: https://github.com/hedyorg/hedy/pull/5134

@jpelay, do you remember why?

2024-04-05 06:54 UTC, rix0rrr commented
Doesn't seem to be easy to re-enable. My struggles will continue in here: https://github.com/hedyorg/hedy/pull/5377

In the mean time, this one should be good to go.

2024-04-05 07:16 UTC, boryanagoncharenko approved these changes

2024-04-05 07:45 UTC, merged