💻 new customize adventure page
hedyorg/hedy pull request #5535
Opened 2024-05-15 15:14 UTC by hasan-sh

Fixes https://github.com/hedyorg/hedy/issues/5086

2024-05-28 16:00 UTC, hasan-sh commented
@Felienne as discussed in the meeting, we need to decide what descriptions we want to put in the solution example and tips tabs:

![image](https://github.com/hedyorg/hedy/assets/20051470/1a1e202c-7b86-43e5-b3b7-1bd1510c1f11)

> NB: the solution example has the editor and the tips is empty!

2024-06-25 20:10 UTC, jpelay reviewed
Hi! Felienne told me to review this since she's busy. 

Seeing the UI I think that the Preview button might be made available on the "Adventure" tab, rather than in the General settings one. I also think the "I agree that my adventure might be made publicly available on Hedy." section can be switched over to the settings tab.

![image](https://github.com/hedyorg/hedy/assets/45865185/003e9267-090a-4a6d-9f4e-ee6cc808c464)

On the solution example section we can put something like:


> This is where the solution of your adventure goes. This can be used if you want to share this adventure with other teacher's, so they can know what your suggested solution is.

If both of these tabs have the editor, maybe we can add the help button to both of them as well

![image](https://github.com/hedyorg/hedy/assets/45865185/b1a4e99d-20f6-4711-aeb8-379939bd4b0c)

2024-06-26 13:15 UTC, hasan-sh commented
> Hi! Felienne told me to review this since she's busy.
> 
> Seeing the UI I think that the Preview button might be made available on the "Adventure" tab, rather than in the General settings one. I also think the "I agree that my adventure might be made publicly available on Hedy." section can be switched over to the settings tab.
> 
> ![image](https://private-user-images.githubusercontent.com/45865185/342910713-003e9267-090a-4a6d-9f4e-ee6cc808c464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDc5MDAsIm5iZiI6MTcxOTQwNzYwMCwicGF0aCI6Ii80NTg2NTE4NS8zNDI5MTA3MTMtMDAzZTkyNjctMDkwYS00YTZkLTlmNGUtZWU2Y2M4MDhjNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEzMTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYzNkNGM0NWVjMGJlNTQzODEzNjIzYzQ2Yjg5NTczZWRiNDI1MmM1MzBkZGY5MDE0ODM2ZjFkNWI4MGQ0OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oR_jhMF32Lo83u54ldUo7nDaXQOahq3MuzVA8ClpxFo)
> 
> On the solution example section we can put something like:
> 
> > This is where the solution of your adventure goes. This can be used if you want to share this adventure with other teacher's, so they can know what your suggested solution is.
> 
> If both of these tabs have the editor, maybe we can add the help button to both of them as well
> 
> ![image](https://private-user-images.githubusercontent.com/45865185/342910578-b1a4e99d-20f6-4711-aeb8-379939bd4b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDc5MDAsIm5iZiI6MTcxOTQwNzYwMCwicGF0aCI6Ii80NTg2NTE4NS8zNDI5MTA1NzgtYjFhNGU5OWQtMjBmNi00NzExLWFlYjgtMzc5OTM5YmQ0YjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEzMTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjJlOTUwZWUzNWYyOTY3MzhmMWUwZmY3NWZmODg3NmE0MTAyNjdlY2I3YzI5N2U1NWE4OTk3NjFmNTM0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4zshZznZsJy0yTJjQ3JWvzlY1sOSXon4GoX5OQSDaJQ)

I like and agree with all suggestions!

2024-06-26 13:16 UTC, hasan-sh commented
Will disable the tips section for now until it's needed and known what content to put in there!

2024-06-26 14:44 UTC, Felienne commented
> Will disable the tips section for now until it's needed and known what content to put in there!

Disabling seems a bit of a heavy strategy?

2024-06-26 14:45 UTC, Felienne commented
> > Will disable the tips section for now until it's needed and known what content to put in there!
> 
> Disabling seems a bit of a heavy strategy?

I think we want something along the lines of: "Here you can add tips to help other teachers help their students"?

2024-06-26 15:11 UTC, hasan-sh commented
> I think we want something along the lines of: "Here you can add tips to help other teachers help their students"?

Sure. How would creating tips look like? Where and how do we list or represent them? 

> Disabling seems a bit of a heavy strategy?

I didn't get any note about it!! Also i thought we could implement it in a separate PR in accordance with the new hedy design that's being created!

2024-06-26 15:16 UTC, Felienne commented
> > I think we want something along the lines of: "Here you can add tips to help other teachers help their students"?
> 
> Sure. How would creating tips look like? Where and how do we list or represent them?

I am lost here, sorry. In the screenshot above, there is already a tab called "tips". I thought you were looking for text to put there to expain what the tips are for. Help me understand what text you need and I can provide it to you.

Please remember I have not looked at this PR, so if you need my input, you need to sketch a bit of context and ask me clear questions (Or ask Jesus, he has seen more of this work, and I am sure he has great ideas too!)

> I didn't get any note about it!! 

I think this has to do with the fact that I don't really understand the question well (again, I have not looked at the PR, just jumping in for being tagged) But surely we can do it in a different PR is that makes more sense, just open an issue so we don't forget.

2024-06-26 15:54 UTC, hasan-sh commented
Well, the mention was in May after i presented the latest status of this PR and you said you'd write more info about how the tips section would look like.  So, I guess the main point is that do you want the tips to be created within an editor as well? Or just a simple textarea?

It just needs some thought to avoid confusion, because if you choose for an editor, there'd be 3 editors in this page!



> But surely we can do it in a different PR is that makes more sense, just open an issue so we don't forget.

Will do!

2024-06-26 16:33 UTC, Felienne commented
> I guess the main point is that do you want the tips to be created within an editor as well? Or just a simple textarea?
> It just needs some thought to avoid confusion, because if you choose for an editor, there'd be 3 editors in this page!

Ok this is a clear question I can answer with ease: I want it to be a simple text box! I had read the confusion as one about content, and thus not understood it. But now you are explaining it well, you are giving alternative options (editor or text) with pros and cons, which is super useful, that really helps me answer quickly!
 
My related question is: how are we going to show the tips, and the model solutions to teachers that want to use the adventures, have we got a plan for that?

2024-06-26 16:33 UTC, Felienne commented
(oops clicked the wrong button when commenting)

2024-07-01 14:01 UTC, Annelein requested changes
Hey @hasan-sh ! Looks good, I've added a few comments and was wondering, is the whole page covered in the Cypress tests now? 

And on a whole different note, I don't really agree with the design of the tabs. Not only because the new design for the Hedy tabs is not implemented yet, so until then teachers might be very confused. But still I think this can be done in a more understandable way. @Felienne @gisellandrade what do you think? Just addressing this now, but can of course be done in a different PR.

2024-07-01 16:34 UTC, hasan-sh commented on tests/cypress/e2e/tools/adventures/adventure.js
> +        cy.get('#custom_adventure_name').clear().type(name);
Can be either

2024-07-01 16:34 UTC, hasan-sh commented on tests/cypress/e2e/for-teacher_page/customize_class_page/customize_class.cy.js
> +    it.only('Is able to reset the adventures and create a new adventure', () => {
Correct!

2024-07-01 16:55 UTC, Felienne commented
> And on a whole different note, I don't really agree with the design of the tabs. Not only because the new design for the Hedy tabs is not implemented yet, so until then teachers might be very confused. But still I think this can be done in a more understandable way. @Felienne @gisellandrade what do you think? Just addressing this now, but can of course be done in a different PR.

Hi @Annelein!

Do you want to make changes to these tabs (that are a bit different from the adventure tabs, because they are here representing different _aspects_ of an adventure)? I am open to looking at what you want it to look like, but I can also imagine we redesign this with the new homepage together.

2024-07-02 11:38 UTC, Annelein commented on tests/cypress/e2e/tools/adventures/adventure.js
> +        cy.get('#custom_adventure_name').clear().type(name);
Yes but data-cy is better practice. So can you change it back to that? https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

2024-07-02 11:50 UTC, Annelein commented
> Do you want to make changes to these tabs (that are a bit different from the adventure tabs, because they are here representing different _aspects_ of an adventure)? I am open to looking at what you want it to look like, but I can also imagine we redesign this with the new homepage together.

Hi @Felienne ! I think it should be a different than the adventure tabs design, so not redesign it with the homepage but septeratly. Because these aren't adventure tabs but they have a whole different meaning/purpose right? Let me know if you get what I mean. 

I was thinking something like this for example:
![Screenshot 2024-07-02 at 13 49 16](https://github.com/hedyorg/hedy/assets/48122190/a8a25fb9-39d5-4592-9896-dc60662fbff2)

2024-07-02 11:50 UTC, Annelein commented
> Hey @hasan-sh ! Looks good, I've added a few comments and was wondering, is the whole page covered in the Cypress tests now?
> 

@hasan-sh what about the Cypress tests?

2024-07-02 12:20 UTC, hasan-sh commented on tests/cypress/e2e/tools/adventures/adventure.js
> +        cy.get('#custom_adventure_name').clear().type(name);
true if you change CSS selectors (like classes!) but id's are rarely changed! Will revert since data-cy's are present either way!

2024-07-02 12:45 UTC, hasan-sh commented
> Hi @Felienne ! I think it should be a different than the adventure tabs design, so not redesign it with the homepage but septeratly. Because these aren't adventure tabs but they have a whole different meaning/purpose right? Let me know if you get what I mean.
> 
> I was thinking something like this for example: ![Screenshot 2024-07-02 at 13 49 16](https://private-user-images.githubusercontent.com/48122190/345009463-a8a25fb9-39d5-4592-9896-dc60662fbff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjQ1MDQsIm5iZiI6MTcxOTkyNDIwNCwicGF0aCI6Ii80ODEyMjE5MC8zNDUwMDk0NjMtYThhMjVmYjktMzlkNS00NTkyLTk4OTYtZGM2MDY2MmZiZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyNDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MDAwMzUxNTc5MGY4YTU2NDRjYWM4OWY4YjEyYzY2ZWY4NzlkYTZhMTIyMTQ1MTNlNWQ0NmQ0YmEyMzkyZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sGRBlx7X0i6B1DnzENUuSVAa3iA6BYMsTVNpj4D18Ko)


I like this since it aligns more with the new redesign, do you wanna push your commit here before we merge?

2024-07-03 11:25 UTC, Annelein approved these changes

2024-07-03 11:54 UTC, merged